/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#ffe785',
          light: '#ffd94d',
          50: '#ffefba',
          100: '#fff3ee',
        },
        action: {
          DEFAULT: '#027fff',
          light: '#0d6efd',
          50: '#e8f4ff',
          100: '#c7e2ff',
        },
        // DESIGN.md "Warm Minimalism" palette
        canvas: '#FECEA1',
        charcoal: {
          DEFAULT: '#2A363B',
          dark: '#1A2328',
          deep: '#0C1A1E',
        },
        coral: {
          DEFAULT: '#F5847C',
          hover: '#E8736B',
        },
        warm: {
          50: '#FFF8F5',
          100: '#F9F3EE',
          200: '#F5ECE7',
        },
        // Material Design 3 tokens (landing page redesign)
        'primary': '#954737',
        'on-primary': '#ffffff',
        'primary-container': '#e98a76',
        'on-primary-container': '#662417',
        'primary-fixed': '#ffdad3',
        'primary-fixed-dim': '#ffb4a4',
        'on-primary-fixed': '#3d0601',
        'on-primary-fixed-variant': '#773122',
        'inverse-primary': '#ffb4a4',
        'secondary': '#576063',
        'on-secondary': '#ffffff',
        'secondary-container': '#d8e1e5',
        'on-secondary-container': '#5b6467',
        'secondary-fixed': '#dbe4e8',
        'secondary-fixed-dim': '#bfc8cc',
        'on-secondary-fixed': '#141d20',
        'on-secondary-fixed-variant': '#3f484b',
        'tertiary': '#685d4e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#afa190',
        'on-tertiary-container': '#41382b',
        'tertiary-fixed': '#f0e0cd',
        'tertiary-fixed-dim': '#d3c4b2',
        'on-tertiary-fixed': '#221a0f',
        'on-tertiary-fixed-variant': '#4f4538',
        'background': '#f9f9ff',
        'on-background': '#151c27',
        'surface': '#f9f9ff',
        'on-surface': '#151c27',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#dce2f3',
        'on-surface-variant': '#54433f',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-dim': '#d3daea',
        'surface-tint': '#954737',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'outline': '#87726e',
        'outline-variant': '#dac1bc',
      },
      fontFamily: {
        sans: ["Montserrat", "'Helvetica Neue'", "Helvetica", "Arial", "sans-serif"],
      },
      boxShadow: {
        card:        'rgba(0,0,0,0.06) 0px 2px 8px 0px, rgba(0,0,0,0.04) 0px 0px 1px 0px',
        'card-hover':'rgba(0,0,0,0.14) 0px 16px 48px 0px, rgba(0,0,0,0.06) 0px 4px 12px 0px',
        ambient:     'rgba(42,54,59,0.12) 0px 12px 32px 0px',
        warm:        'rgba(245,132,124,0.25) 0px 8px 24px 0px',
        float:       'rgba(0,0,0,0.16) 0px 24px 64px 0px, rgba(0,0,0,0.08) 0px 4px 16px 0px',
        glow:        'rgba(233,138,118,0.30) 0px 8px 32px 0px, rgba(233,138,118,0.10) 0px 2px 8px 0px',
        subtle:      'rgba(0,0,0,0.04) 0px 2px 8px 0px, rgba(0,0,0,0.02) 0px 1px 2px 0px',
        inner:       'inset 0 1px 0 rgba(255,255,255,0.15), inset 0 -1px 0 rgba(0,0,0,0.06)',
      },
      keyframes: {
        'slide-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.5' },
        },
      },
      animation: {
        'slide-in': 'slide-in 0.2s ease-out',
        'fade-up':  'fade-up 0.6s ease-out both',
        'scale-in': 'scale-in 0.18s cubic-bezier(0.16,1,0.3,1)',
        'pulse-dot':'pulse-dot 1.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
